### ISSUE TITLE
v2024.6.18 a cassé le mod ?

### ISSUE THREAD

**Issue by Lutakh** [EnoPM/EnoPM.BetterVanilla#1]
Bonjour,

Tout d'abord merci pour le travail et pour ce mod qui est très agréable à utiliser.
Merci d'avoir pris la décision de le publier à tout le monde.

Depuis la mise à jour Among US v2024.6.18, je n'ai plus aucune fonctionnalité du mod. J'ai bien l'icône du mod en haut à droite mais aucune information. 

Est-ce qu'il y a un moyen d'ouvrir un menu pour configurer le mod ? Je l'ai toujours utilisé sans rien modifier car je ne sais pas si on peut ouvrir un menu quelque part.

J'ai tenté de réinstaller les fichiers du mod dans le dossier Among US après la mise à jour mais sans succès.

Merci pour l'aide.

**Comment by EnoPM** [comment]
Je viens de publier une mise à jour pour Among Us v2024.6.18
