### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Twitch-Antho** [EnoPM/EnoPM.BetterVanilla#2]
Slt, peux-tu me dire quel est le but de ton mod ?
Je vois pas de description...
Puis-je avoir une liste ou une grande explication. Merci

**Comment by lucie-bechtold** [comment]
Le mod ajoute des possibilités de customization des games plus grandes (changer le timing du réacteur, éditer à la seconde près, voir même la demi-seconde les autres settings (kill cooldown, temps de vote, etc...)
Le vrai grand intérêt apparait une fois mort. Un crewmate mort peut dézoomer son écran, voir les tâches effectuées, les imposteurs sont marqués d'une banner, on peut voir les gens sur la map, et on peut voir qui vote comment.
Evidemment, un imposteur mort ne pourra pas dézoomer son écran, et pour éviter les tricheries il ne pourra pas non plus voir la position des gens sur la map.
